### ISSUE TITLE
Warnings: verify_email.LinkCounter

### ISSUE THREAD

**Issue by drangovski** [foo290/Django-Verify-Email#11]
Hello, this is awesome package, you have saved me just right on time :) Thank you very much!

Everything is working properly so far, I am just seeing this message in the console:

```
verify_email.LinkCounter: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the VerifyEmailConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```

It seems that adding `default_auto_field = 'django.db.models.AutoField'` in apps.VerifyEmailConfig fix the warning, but anyway it may be something that you need to check out.

Thank you!

**Comment by foo290** [comment]
Thank you very much for reporting this, I appreciate your input. I will definitely look for it.  :D
