### ISSUE TITLE
upgrading from v0 to v1, existing users have no link counter.

### ISSUE THREAD

**Issue by kirosharlequin** [foo290/Django-Verify-Email#12]
perhaps I have done something wrong with the update, but when upgrading a system existing users cant log in because they dont have a link counter associated with them.

perhaps the initial migration should include something which creates one for existing users? 

RelatedObjectDoesNotExist at /accounts/login/
User has no linkcounter.

\verify_email\signals.py, line 14, in save_count
    instance.linkcounter.save()

**Comment by foo290** [comment]
Hmm... cool, will look into this ASAP. Thanks for reporting :p

**Comment by foo290** [comment]
fixed :)
