### ISSUE TITLE
Link on pypi

### ISSUE THREAD

**Issue by adeeas** [foo290/Django-Verify-Email#18]
Sorry I'm new to github and idk if this is a real issue but I spent hours downloading this package but it turns out the link was for v0.0.5. 
https://pypi.org/project/Django-Verify-Email/

**Comment by foo290** [comment]
![image](https://user-images.githubusercontent.com/32377892/120091501-475c8e00-c129-11eb-990b-d2589be1404a.png)

I am sorry, I don't understand, are u saying you are not able to download it via pip? btw the link redirects you to the latest version.

**Comment by adeeas** [comment]
I mean when i copied that it downloaded the old version. I had to manually upgrade to the current one

**Comment by foo290** [comment]
I'll look it up, thanks for reporting 😃
