### ISSUE TITLE
Foreign Key Constrained Error

### ISSUE THREAD

**Issue by fredypasaud** [foo290/Django-Verify-Email#19]
Hello, it's not really an issue actually but I'm confused about how to implement your project in my project. My project use a username as the authentication key. So the first user will have to register and their password, and then that information will be saved. After that user will completing a signup form with their details and e-mail field in it. Now, everytime I try to implement send_verification_email in my second sign up form I always get an error that says foreign key constrained error. My guess because your project save the user, and my project also save the form and user django just doesn't know which user to save. Do I need to rework my project or is there any way I can implement your application in my project. Let me know if you need more information I would be glad to help. Thank you

**Comment by adeeas** [comment]
I'm not sure if I'm right but I think it's because ure saving the registration form yourself too. You don't need to do that. 
Just check if form is valid, then call send_verification_email and pass the form as argument. It'll save the info for u

**Comment by fredypasaud** [comment]
I guess that too, i'll try without saving my user then.
