### ISSUE TITLE
Can we use this without django forms?

### ISSUE THREAD

**Issue by akshith6212** [foo290/Django-Verify-Email#21]
Hello Developers, 

I am registering the user in my app using a custom html form submission, Is there any way to use this tool in my app so that I can use this one?

Thankyou.

**Comment by foo290** [comment]
probably not, haven't tried it but I guess not, this is majorly dependent on Django forms.

**Comment by snehilbanawal** [comment]
> 
> 
> Hello Developers,
> 
> I am registering the user in my app using a custom html form submission, Is there any way to use this tool in my app so that I can use this one?
> 
> Thankyou.

I am currently using this without django forms. Like so: send_verification_email(request,new_user).
I am encountering errors but it works. I have a custom user model and am initializing the new_user with User model object.

**Comment by akshith6212** [comment]
Oh that's great I will definitely try with that. Thankyou @snehilbanawal .

**Comment by pssolanki111** [comment]
@snehilbanawal Hey snehil, Mind explaining how you achieved it? 

Do you mean you create a user object with your user model, 
```py
new_user = your_user_model.objects.create(whatever='val')
```
 then pass that to `send_verification_email` like
```py
send_verification_email(request,new_user)
```

**Comment by pssolanki111** [comment]
@foo290 also I was successfully able to override some methods and functions to make this work with `User` objects instead of `forms`. If that's something you'd like added to the lib, I can put together a PR.

**Comment by foo290** [comment]
sure, we can just inspect if the passed object is of user object or form and proceed based on that. That'll make it work without Django forms without any need to override method.

**Comment by pssolanki111** [comment]
> That'll make it work without Django forms without any need to override method.

oh of course, overriding is only necessary when I'm needing to make changes to it without modifying the source.

> sure, we can just inspect if the passed object is of user object or form and proceed based on that

it's a very small change indeed. the function also need a signature change to include `email=None` so that the view gets the email address because there is no form being passed.  @foo290
