### ISSUE TITLE
Resend verification email documentation

### ISSUE THREAD

**Issue by kirosharlequin** [foo290/Django-Verify-Email#25]
I'm trying to implement the re-sending of links, but the documentation doesn't make it clear how to do that. I had a read through the code and saw that it takes the email and the token but does not say how to get them and it doesnt look like they are saved after the first email is sent

what I hope I can do with this is have a form on my log in  pages where a user can input their email address and have the email resent, is that possible?

**Comment by foo290** [comment]
It is possible, but you'll have to do most of the work, as this is not included in the package :/
