### ISSUE TITLE
Not Sending verification email

### ISSUE THREAD

**Issue by gluttonyxx** [foo290/Django-Verify-Email#26]
Hi, I am very new to Django and I followed all the steps. I still could not send the verification email. On creation of a new account it set the account to inactive but it did not send the email address a verification email. Please do advise on how to proceed, I think it might be a mail server issue. Attaching my mail server config here, please do let me know what I am doing wrong. 
Thanks in advance!
![image](https://user-images.githubusercontent.com/51082592/140600815-b621a8a3-3a66-44cc-8c6b-8fb8d934de9e.png)

**Comment by foo290** [comment]
Your configs look fine, please reassure you are calling the right method to send email and if you have 2fa on your Gmail then you might have to create an app password for that.

**Comment by gluttonyxx** [comment]
I solved this issue and it began sending a verification email but every time I click on verify it shows that the verification has failed.
![image](https://user-images.githubusercontent.com/51082592/141232430-ae189e4c-21ed-4020-9337-7e11a554b24b.png)

Any solution to the same?

**Comment by gluttonyxx** [comment]
UPDATE : I realised I was not using this piece of code -

inactive_user.cleaned_data['email']

# Output : test-user123@gmail.com

Where should that be used? Please do advise me on the same

**Comment by foo290** [comment]
This is for further use of inactive users in code, prolly has nothing to do with the issue you are facing.
Pay attention to `last login` (if you are altering it in any way) field of user, coz that is used to make a hashed token for users.

**Comment by gluttonyxx** [comment]
I am not altering last login or any other code in any way, I have just added it as it is.

**Comment by foo290** [comment]
paste the error stack trace please

**Comment by gluttonyxx** [comment]
This is my console output
![image](https://user-images.githubusercontent.com/51082592/141279642-92f26986-ec2e-4e8b-97c4-39eb95c00f66.png)

**Comment by gluttonyxx** [comment]
Slightly longer error stack trace from another attempt at making it work
![image](https://user-images.githubusercontent.com/51082592/141606418-6eadee77-536b-41f9-be63-d4ef14e8912f.png)

**Comment by foo290** [comment]
`user has no link counter` did you apply migrations?

**Comment by gluttonyxx** [comment]
Yes
![image](https://user-images.githubusercontent.com/51082592/141606737-2088491c-0e86-4b30-a529-8969296bb968.png)

**Comment by gluttonyxx** [comment]
@foo290 looking forward to your suggestion to fix this issue, do advise!

**Comment by foo290** [comment]
Please make sure of [link expiring](https://github.com/foo290/Django-Verify-Email#expiration-of-link-and-resending-emails-) configs, as the logs shown in screenshots are not much information, I cannot deduct where exactly the problem lies.

**Comment by millforma** [comment]
Hello Everyone, I'm facing the same issue @gluttonyxx did u solve it ?

**Comment by millforma** [comment]
My last_login field is <null> can this be the problem ?

**Comment by Ronniie** [comment]
> UPDATE : I realised I was not using this piece of code -
> 
> inactive_user.cleaned_data['email']
> 
> # Output : [test-user123@gmail.com](mailto:test-user123@gmail.com)
> Where should that be used? Please do advise me on the same

How were you able to fix this? Running into similar issues where I'm getting no response, no emails sending.
Thanks!

**Comment by foo290** [comment]
might be fixed in new release
