### ISSUE TITLE
Verify_email -> Link Counters causes __str__ return non-string error

### ISSUE THREAD

**Issue by eraykuyumcu** [foo290/Django-Verify-Email#27]
Thanks for your very nice Django addition guys

I have a custom user model and link counter is causes __str__ returned non-string (type NoneType) when try to delete a user. 

![image](https://user-images.githubusercontent.com/87933896/141016178-10403611-8b2f-40c3-b8a5-4bb327efbe72.png)

Thanks for the advance.

**Comment by foo290** [comment]
I don't know the exact cause of that, but release a patch just in case, that should fix the error.
Please re-install `pip install Django-Verify-Email`

Sorry for the inconvenience and thanks for reporting 😄

**Comment by eraykuyumcu** [comment]
Thanks for the very fast response. Have a nice day 😊
