### ISSUE TITLE
Verification fails unless setting LOGIN_URL in settings.py

### ISSUE THREAD

**Issue by uranderu** [foo290/Django-Verify-Email#29]
Hi,

It seems that verification doesn't work until I set the "LOGIN_URL" variable in my settings.py.
If I don't do this and press on the "Verify" button in my e-mail I get this:
![Screenshot from 2021-12-30 14-54-03](https://user-images.githubusercontent.com/71091366/147758137-fd7f4229-d183-4ea7-b813-4111ccab0395.png)
Refreshing or reclicking the button gives me the "Verification Failed" page. And indeed my user isn't activated. However when I set the "LOGIN_URL" variable in my settings.py everything works.

I use the standard Django authentication urls implemented by this line:
`path('accounts/', include('django.contrib.auth.urls'))`

**Comment by foo290** [comment]
`LOGIN_URL` is required, even if you use standard Django authentication
