### ISSUE TITLE
Import in views is errorring out.

### ISSUE THREAD

**Issue by andrewingram928** [foo290/Django-Verify-Email#3]
@foo290  Import in views is erroring out.
![Screenshot 2020-12-14 214457](https://user-images.githubusercontent.com/59937941/102176135-a9645800-3e55-11eb-9c1c-d5469b72c0b4.png)

**Comment by foo290** [comment]
**its** 
from verify_email.email_handler import **send_verification_email**

refer to <a href="https://github.com/foo290/Django-Verify-Email#step-3--">docs...</a>

**Comment by andrewingram928** [comment]
Oops, sorry about that. 

This link needs editing.

https://pypi.org/project/Django-Verify-Email/

**Comment by foo290** [comment]
ahh... thanks 👍🏻

**Comment by andrewingram928** [comment]
> ahh... thanks 👍🏻
<3
