### ISSUE TITLE
Django-Verify-Email always throw the token failed page

### ISSUE THREAD

**Issue by knightblood777** [foo290/Django-Verify-Email#31]
hello when i signup with a user the email of account activation is being sent to my inbox,but after i click it redirect me to the verification failed page saying that there is something with the link (from the first time click that happens).

**Comment by JonK123** [comment]
Solved on my side by deleting existing users.

**Comment by foo290** [comment]
might be fixed in new release

**Comment by ralixit** [comment]
Hello when I signup with a new user - The new user receives a verify email - but when the [verify] link gets clicked it's response is a verification failed page  : Invalid Link
This link is invalid or been used already, we cannot verify using this link.

`http://127.0.0.1:8000/verification/user/verify-email/Ym9hcmRtZW1iZXJAdGllcnJhc2t5LmNvbQ==/YjN5MWRkLWEyMTJkMjY5YzE3OWI3YTgwOWEwMDI1M2E0YjA5NjUz/`

This link seems to be missing the <useremail> in path(f'user/verify-email/<useremail>/<usertoken>/'

I'm not sure if my custom Member is the issue in regards to :email = models.EmailField(_('email address'), unique=True)

```
class Member(AbstractBaseUser, PermissionsMixin):

    # INITIAL MEMBER BASIC INFORMATION (05) #
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    phone = models.CharField(_('phone'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
```
