### ISSUE TITLE
not local sender over smtp

### ISSUE THREAD

**Issue by tender322** [foo290/Django-Verify-Email#35]
Error code:
`Error in sending email.
Error code: 550
Error: b'not local sender over smtp'
`
Hello , I did everything step by step, but nothing comes out.

**Comment by tender322** [comment]
My test email is working.

**Comment by foo290** [comment]
![image](https://user-images.githubusercontent.com/32377892/158065688-e8c9e354-d044-4094-b9b4-2fc069f50698.png)

it seems related to auth

**Comment by tender322** [comment]
But test sends work
