### ISSUE TITLE
Error when re-requesting verification email

### ISSUE THREAD

**Issue by sebastianhaas** [foo290/Django-Verify-Email#38]
First off: Thank you for your timing creating this library. It is very much appreciated!

I encountered a little issue when re-requesting a token in your latest update:

```
ValueError at /verification/user/verify-email/request-new-link/

The view verify_email.views.request_new_link didn't return an HttpResponse object. It returned None instead.
```

Django Version: 3.2.6
Python Version: 3.9.12
Library Version: 2.0.1 

After a little investigation, I found that the issues is a result from your newly introduced form:

```python
class RequestNewVerificationEmail(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['email']
```
(forms.py)

Now, I got a custom user model like this:
```python
class CustomUser(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    username = None
    email = models.EmailField(
        unique=True, verbose_name=_("email address"), help_text=_("Your email address.")
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
```

By adding the `unique=True` flag on the email field, your form fails to validate since the email address that is entered again as a confirmation already exists in the database and Django tries to guard from a double insertion. Now I assume that adding a unique flag on the email column is a fairly reasonable thing to do, especially for those use cases where you don't have an additional username.

Changing `RequestNewVerificationEmail` to the following resolves the issue in a way that is probably even a bit more robust against all kinds of different custom user model configurations:

```python
class RequestNewVerificationEmail(forms.Form):
    email = forms.EmailField(
        label=get_user_model()._meta.get_field("email").verbose_name,
        help_text=get_user_model()._meta.get_field("email").help_text,
    )
```

Please let me know what you think, I'll be happy to provide a PR for this.

**Comment by foo290** [comment]
Hi, Thanks for the contribution, Yes I think that'd be best to make a normal form instead of a model form. Please make a PR regarding it, I'll merge it asap as its a bug.
