### ISSUE TITLE
Link is "_blank" in the Verification E-Mail

### ISSUE THREAD

**Issue by Grreg** [foo290/Django-Verify-Email#4]
Hey!
Thanks for the plugin, but I have some trouble make it working. The link is being generated seems to be None or Empty as in the Email its with `a href="_blank"`. I tried to debug it but could not found any issues.

I am using "django-use-email-as-username", but it basically simply removes the user.name, but the rest is working the same. Checked your code and it does not look like you use the user.name, so there should be no issues.

And I currently run it on localhost (with using an external SMTP Server for Mails) for testing, could this make issues with the link generation?

![image](https://user-images.githubusercontent.com/1329880/105576688-d4a36680-5d74-11eb-8a83-53e7c704858f.png)

**Comment by Grreg** [comment]
The interesting part ist, when I call this link generation on an existing Object it works like a charme.
`    # Testing Verifcation link
    test = _VerifyEmail()
    inactive_user = request.user
    useremail = request.user.email
    current_site = get_current_site(request)
    test._VerifyEmail__make_verification_url(current_site, inactive_user, useremail)
    token = test._VerifyEmail__get_hashed_token(inactive_user)
    email_enc = urlsafe_b64encode(str(useremail).encode('utf-8')).decode('utf-8')
    link = f"{current_site}/verification/user/verify-email/{email_enc}/{token}/"
    print(link)`

![image](https://user-images.githubusercontent.com/1329880/105577054-6613d800-5d77-11eb-8e1c-39eca46d22c3.png)

**Comment by foo290** [comment]
By the image you posted, are you using a custom template for email? And that is ```target="_blank"``` ,  href should be ```href={{link}}```

**Comment by Grreg** [comment]
I did not configured any template, but if you say its not the default template than I need to check my settings. Will let you know later this afternoon, thanks a lot! Its an important hint that this is - against my thoughts - not the default template.

**Comment by Grreg** [comment]
Ok, I think I found the issue. In the real source code of the mail the links is correct. And I am also using the default HTML Template from your comfortable package :)  (Thanks!)

But, it seems like either because it is missing the http:// prefix in the url OR because its pointing to localhost, Google Chrome translates it into a _blank. Same happend on my iPhone. Maybe kinda prevention to access localstuff from external mails, dont know.

**Comment by Grreg** [comment]
Real Source code of the mail:
```
 <a href="127.0.0.1:8000/verification/user/verify-email/Z3JlZ29yQGdydXN6a2Eub25saW5l/YWd4ZzBrLTRmYjk2YjgzNjVhMWRjMWM3NTM0ZDY5NGE2NjA5NzZl/" class="my-button" >Verify</a>
 ```
 The source code that shows up in the Browser Dev Tools:
 ```
 <a class="my-button" target="_blank">Verify</a>
 ```

**Comment by foo290** [comment]
It's caused by missing **http://**, It works on some mailbox like windows mail but Gmail web is blocking it as it does not contains **http://**. Anyway, found the issue and m fixing it by building absolute URL by ```request.build_absolute_uri()```. **issue will be fixed and live in the next half hour**. <br> Thanks for informing. Happy coding 😀

**Comment by Grreg** [comment]
Wow! Thats really friendly you, thank you very much!

Yes, gonna close this as its kinda workarounded for now and you are already working on a patch! Thanks.

Ps. in this line is a typo: https://github.com/foo290/Django-Verify-Email/blob/main/verify_email/templates/verify_email/email_verification_msg.html#L59
It should be probably "received". I tried to fix it, but had issues with my git setup to work with github somehow :( Gonna have a look at this later.

Thank you very much for providing this Package, it helped me a lot! :)
