### ISSUE TITLE
Use `get_username` instead of `username`

### ISSUE THREAD

**Issue by grmoon** [foo290/Django-Verify-Email#40]
In the `__str__` method of `LinkCounter` in `models.py`, use `get_username()` instead of `username` to account for apps that have changed the `USERNAME_FIELD` of their user model.

See [this link](https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser.get_username) for more info. Relevant code: https://github.com/foo290/Django-Verify-Email/blob/5ba6f645d220ed1d9bd4486f7aed9272f84d711b/verify_email/models.py#L11-L12

**Comment by foo290** [comment]
Thank you so much for the improvements :)
