### ISSUE TITLE
`request_new_link` does not account for potentially unique email addresses.

### ISSUE THREAD

**Issue by grmoon** [foo290/Django-Verify-Email#42]
`RequestNewVerificationEmail` is a `ModelForm` for the user model of an app. If the user model requires a unique email, then `form.is_valid` will be `False`. If this form is meant to create a new user (which I don't think it is?), then it should be robust enough to handle varied user models (e.g. what if a field besides email is required?). Otherwise, it probably shouldn't be a `ModelForm`, just a normal form with an `EmailField`

**Comment by sebastianhaas** [comment]
Please take a look at https://github.com/foo290/Django-Verify-Email/issues/38 from 15 hours before your post :)
