### ISSUE TITLE
{{link}} is not working

### ISSUE THREAD

**Issue by piotrPeplinski** [foo290/Django-Verify-Email#5]
I'm using default templates and the verification link does not have an href attribute: 
`<a class="m_-5654556666167927182my-button">Verify</a>`
seems like {{link}} is not working properly.

**Comment by foo290** [comment]
Hi, Thanks for the feedback! This issue has been fixed in the latest release **pip install Django-Verify-Email==0.0.5** <br> you may close the issue. Happy coding :)
