### ISSUE TITLE
Invalid Link This link is invalid or been used already, we cannot verify using this link.

### ISSUE THREAD

**Issue by xAli-1** [foo290/Django-Verify-Email#53]
Hi
I got error same as #49 

when new user click on [verify] link, this error well show:
 "Invalid Link This link is invalid or been used already, we cannot verify using this link."

`http://domain.ltd/verification/user/verify-email/aGlwc2FuaXJ0aUB2dXNyYS5jb20=/YjYwbGhnLWE5ZTM2YzExZWJlYTFkY2E4NjQ4ZmM3NzUwNjI4ZGRl/`

`from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    name = models.CharField(max_length=100, blank=True, null=True)   
`
**Email inherited from AbstractUser**

any idea how to fix it?

**Comment by bgorman87** [comment]
From line 101 in views.py
 ```
except InvalidToken:
        return render(
            request,
            template_name=failed_template,
            context={
                'msg': 'This link is invalid or been used already, we cannot verify using this link.',
                'status': 'Invalid Link',
            }
        )
```
Something about your configuration isn't validating the token from what I can tell. Not entirely sure what would cause that. Have you edited the email handler, or any of the url settings, or anything to do with the verify_email package?

**Comment by xAli-1** [comment]
i got the same code from line 105.

i didn't do any thing in  `.venv/lib/python3.8/site-packages/verify_email/ ` 
 i am new to Django i barely followed instructions from [https://pypi.org/project/Django-Verify-Email/](url)


my users.views.py

`...
from verify_email.email_handler import send_verification_email

def register_view(request):
    form = CustomCreationForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        inactive_user = send_verification_email(request, form) # https://pypi.org/project/Django-Verify-Email/ Step 4
        form.save(request)
        messages.add_message(request, SUCCESS, _('Thank you for registering.'))
        return redirect('login_view')
    context = {
        'form': form
    }
    return render(request, 'signup.html', context)`

# i got an error form my code editor "inactive_user" is not accessed Pylance

**Comment by foo290** [comment]
`form.save(request)` can u not save the form manually?

form is saved automatically after user is marked as inactive at the time of registration hence before verification

**Comment by xAli-1** [comment]
how can i fix it.
i am new to Django and programing.

**Comment by foo290** [comment]
in your register function in views.py

```
from verify_email.email_handler import send_verification_email

def register_view(request):
    form = CustomCreationForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        inactive_user = send_verification_email(request, form) # https://pypi.org/project/Django-Verify-Email/ Step 4
        # form.save(request)  =========================================>>> REMOVE THISSSSSS!!
        messages.add_message(request, SUCCESS, _('Thank you for registering.'))
        return redirect('login_view')
    context = {
        'form': form
    }
    return render(request, 'signup.html', context)
```

**Comment by xAli-1** [comment]
> Try removing or commenting out your `form.save(request)` line. The verify_email package handles everything you need. Your IDE will also show/say inactive_user isn't used because it isn't.

# Verification Successful!
