### ISSUE TITLE
NoReverseMatch after clicking verification link

### ISSUE THREAD

**Issue by bphariharan1301** [foo290/Django-Verify-Email#59]
I keep on getting this issue:-

 > NoReverseMatch at /verification/user/verify-email/dGVzdEBnbWFpbC5jb20=/Ymt2OGowLWJlM2ZkMWZmNTgxMWIyYjFjNzNiYjIwYTgyMjg3MjBh/
Reverse for 'accounts.views.login' not found. 'accounts.views.login' is not a valid view function or pattern name. 

Which indeed exists under accounts/urls.py and the function is at accounts/views.py

accounts/urls.py
`urlpatterns = [
    path('login/', views.login, name='login'),
]`

And when I looked into the app_configurations.py file I found that the LOGIN_URL parameter was taking a default value which was not present in the application. So, I tried adding that under my_project/settings.py 

`LOGIN_URL = 'accounts.views.login'`

But, I do not know why it again throws the same error. 
Can you please tell me where I'm going wrong

Thank you

> PS: I have also attached a image of the error [here](https://user-images.githubusercontent.com/56637724/224368674-ec28cff6-9e5d-459b-97d1-ea494eccf29c.png)

**Comment by foo290** [comment]
Try `LOGIN_URL='login'`, basically same as u'hve given `name='login'` in urlpatterns path

**Comment by bphariharan1301** [comment]
Thanks you so much man!
It worked!

Out of curiosity why it didn't work when I gave 

`LOGIN_URL = 'accounts.views.login'` 
Considering both means the same

Thank you!

**Comment by foo290** [comment]
u are providing `name=` in pattern for that view

**Comment by fevrec** [comment]
had the same problem, thanks for the answer !
