### ISSUE TITLE
Reverse for '/accounts/login/' not found. '/accounts/login/' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by mortazaamer20** [foo290/Django-Verify-Email#64]
everything worked correctly but when the user hit the verify button in the massage an error happed says 

NoReverseMatch at /verification/user/verify-email/bW9ydGF6YS5hbWVyMjBAZ21haWwuY29t/YnBkbTVmLTEyNWNlNWY5ZjZjMTgzYThhMTdlZTUxNTNiOGEyNDM4/
Reverse for '/accounts/login/' not found. '/accounts/login/' is not a valid view function or pattern name.

anyone can help me ?

**Comment by h-enes-simsek** [comment]
You need to have a login page url. Because if the verification is successful, you are being redirected into a template page that has a link which is your login page. So you have two options:
- Provide a custom template
- Add a login page (add LOGIN_URL to settings and use it in url configuration)

**Comment by mortazaamer20** [comment]
> You need to have a login page url. Because if the verification is successful, you are being redirected into a template page that has a link which is your login page. So you have two options:
> 
> * Provide a custom template
> * Add a login page (add LOGIN_URL to settings and use it in url configuration)

THANK YOU!! it worked now thanks alot
