### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by sebastianhaas** [foo290/Django-Verify-Email#79]
Thank you for your work on this package!

Is this project still actively maintained? Is there a chance to add maintainers to help ease the load? I would very much appreciate using this repository as a common base rather than having to maintain a separate fork.

Kindest regards
Sebastian

**Comment by irfanzainudin** [comment]
I also second this, as I'm considering using this package for my app. Please let us know, thanks!

**Comment by foo290** [comment]
hey fellas! embarrassed to reply after months, but yeah, lemme know if I can add collaborators
