### ISSUE TITLE
Link Expiry and Resend Activation 

### ISSUE THREAD

**Issue by firaki12345-cmd** [foo290/Django-Verify-Email#9]
Hi,first of all thank you so much for making such an awesome Third party package for Django. can you help me out in two main issues i have

1. How long does the verification Link Last and how can i Edit it ?
2. If it gets expired, how can I resend the link to User for email verification ?

Thanks and sorry for the trouble

**Comment by foo290** [comment]
hello :p, currently link stays up until it's been clicked at least once, but considering your issue, I'll work on this feature this weekend with fully customizable attributes. Thanks for the suggestion and happy coding! :)

**Comment by firaki12345-cmd** [comment]
Hi, thanks for the quick reply and you can also check out allatuh for
django, it seems pretty similar but wth bit more options :)

**Comment by foo290** [comment]
[update 1.0.5](https://github.com/foo290/Django-Verify-Email#expiration-of-link-and-resending-emails-)
